type Account {
  email: String! @unique
  profile: Profile! @relation
}

type Profile {
  name: String! 
  applications: [Application!] @relation
}

type Application {
  company: String!
  role: String!
  initialExcitement: Int  
  currentExcitment: Int
  interviews: [Interview!] @relation
}

type Interview {
  date: String!
  type: String!
  nerves: Int
  notes: String!
  excitement: Int
}

type Query {
  accounts: [Account]
  accountByEmail(email: String!): [Account!]
}
